name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:

    strategy:
      matrix:
        version: [ 11, 14, 17 ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
